### ISSUE TITLE
Labels do not propagate to node(s) from machineset API

### ISSUE THREAD

**Issue by asm582** [openshift/machine-api-operator#1077]
Machinset API allows the setting of labels but those labels do not propagate to node(s), Ideally we would want labels to flow as:

user labels on -> Machineset -> Machine -> (does not happen)Node.

Is the above behavior by design?

**Comment by miyadav** [comment]
@asm582 , you can refer - https://github.com/openshift/machine-api-operator/blob/master/FAQ.md#which-annotations-and-labels-get-added-to-nodes 

Basically if you provide labels like 
```
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: xxx
      machine.openshift.io/cluster-api-machineset: xxx
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: xxx
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: xxxx
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
         machine.openshift.io/userdefined: ""
         userdefined: "1-userdefined"
```

It will work ...
