### ISSUE TITLE
MachineSets with Node Auto-Provisioning feature

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/machine-api-operator#1270]
## About

Most of the managed Kubernetes services out there currently supports a feature commonly called as "Node Auto-Provisioning (NAP), which allows the Kubernetes to scale the worker nodes using dynamic instance types/size according the resources being requested to the cluster (PodSpecs).

- EKS: https://archive.eksworkshop.com/beginner/085_scaling_karpenter/automatic_node_provisioning/
- GKE: https://cloud.google.com/kubernetes-engine/docs/concepts/node-auto-provisioning
- AKS: https://learn.microsoft.com/en-us/azure/aks/node-autoprovision

## Request

It would be nice to have similar capability on OpenShift Machine API, allowing the administrator to define a range of valid cloud instance type/sizes, and let the controller to choose the best option to accommodate cluster capacity requirements. It could not only provide Just-in-Time Node Provisioning but also Consolidation capabilities, like Karpenter provides.

https://karpenter.sh/docs/concepts/nodepools/

## Example

```
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
          minValues: 2
        - key: karpenter.k8s.aws/instance-family
          operator: Exists
          minValues: 5
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["m5","m5d","c5","c5d","c4","r4"]
          minValues: 3
        - key: node.kubernetes.io/instance-type
          operator: Exists
          minValues: 10
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
```
