### ISSUE TITLE
MachineHealthCheck not working if Node goes down

### ISSUE THREAD

**Issue by kahootali** [openshift/machine-api-operator#690]
I have Openshift 4.5.4 cluster on AWS, and I am using mixture of Spot Instances & on-demand instances as worker nodes, the issue is Spot Instances can terminate at any time, so I was looking into MachineHealthCheck, and applied one but it isn't doing anything. What happens is node gets terminated, Machine goes into Failed State, MachineSet shows 0 of 1 instance, MachineHealthCheck also shows 0 healthy Machines,but doesn't do anything to bring back the node...
Below is my MachineHealthCheck manifest

```
apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: spot-node
  namespace: openshift-machine-api
spec:
  maxUnhealthy: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machineset: lab-spot-node
  unhealthyConditions:
    - status: Unknown
      timeout: 60s
      type: Ready
    - status: 'False'
      timeout: 60s
      type: Ready
    - status: NotReady
      timeout: 60s
      type: Ready
status:
  currentHealthy: 0
  expectedMachines: 1
```
Is there any issue in the manifest or my understanding?
